'use strict';

const crypto = require('crypto');

const SYSTEM_ID_PATTERN = /^[A-Z][A-Z0-9]*-[A-F0-9]{20}$/;

function randomIdentifierSuffix() {
  return crypto.randomBytes(10).toString('hex').toUpperCase();
}

function createSystemId(prefix) {
  const cleanPrefix = String(prefix || '').trim().toUpperCase();
  if (!/^[A-Z][A-Z0-9]*$/.test(cleanPrefix)) {
    throw new Error('System ID prefix is invalid.');
  }
  return `${cleanPrefix}-${randomIdentifierSuffix()}`;
}

function createBlockFarmId() {
  return createSystemId('BF');
}

function createFieldId() {
  return createSystemId('FLD');
}

function assertNoClientIdentity(body, keys, entityLabel) {
  const suppliedKey = keys.find(key => Object.prototype.hasOwnProperty.call(body || {}, key));
  if (suppliedKey) {
    const error = new Error(`${entityLabel} ID is generated by the server and cannot be supplied or changed by a client.`);
    error.status = 400;
    throw error;
  }
}

function readDevelopmentSeedId(req, key = 'id') {
  const enabled = process.env.NODE_ENV !== 'production'
    && process.env.HUGPONG_ALLOW_DEV_TEST_ACCOUNTS === 'true'
    && String(req?.get?.('x-hugpong-development-seed') || '').toLowerCase() === 'true';
  if (!enabled) return null;
  const value = String(req?.body?.[key] || '').trim().toUpperCase();
  if (!/^[A-Z0-9_-]{3,80}$/.test(value)) throw new Error('Development seed ID is invalid.');
  return value;
}

module.exports = {
  SYSTEM_ID_PATTERN,
  createSystemId,
  createBlockFarmId,
  createFieldId,
  assertNoClientIdentity,
  readDevelopmentSeedId
};
