import React, { useEffect, useState } from 'react';
import { Modal, FormField, Input, Select, Button } from '../ui';
import { Layers } from 'lucide-react';
import { createField } from '../../services/fieldsService';

const currentYear = new Date().getFullYear();
const CROP_YEAR_PREVIEW = `${currentYear}–${currentYear + 1}`;

export default function FieldEnrollmentModal({
  isOpen = false,
  onClose,
  blockFarms = [],
  memberUsers = [],
  defaultBlockFarmId = '',
  onSuccess
}) {
  const [blockFarmId, setBlockFarmId] = useState(defaultBlockFarmId);
  const [memberUserId, setMemberUserId] = useState('');
  const [areaHa, setAreaHa] = useState('');

  const [errors, setErrors] = useState({});
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [serverError, setServerError] = useState(null);

  useEffect(() => {
    if (!isOpen) return;
    setBlockFarmId(defaultBlockFarmId);
    setMemberUserId('');
    setAreaHa('');
    setErrors({});
    setServerError(null);
  }, [isOpen, defaultBlockFarmId]);

  const handleBlockFarmChange = (e) => {
    setBlockFarmId(e.target.value);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setServerError(null);

    const validation = {};
    const cleanBf = blockFarmId || defaultBlockFarmId;
    if (!cleanBf) {
      validation.blockFarmId = 'Parent Block Farm is required.';
    }

    const numHa = Number(areaHa);
    if (!areaHa || isNaN(numHa) || numHa <= 0) {
      validation.areaHa = 'Enter a valid area in hectares (> 0).';
    }

    if (Object.keys(validation).length > 0) {
      setErrors(validation);
      return;
    }

    setIsSubmitting(true);
    try {
      const payload = {
        blockFarmId: cleanBf,
        memberUserId: memberUserId || null,
        areaHa: numHa
      };

      await createField(payload);
      setIsSubmitting(false);
      if (onSuccess) onSuccess();
      onClose();
    } catch (err) {
      console.error('[FieldEnrollment] Error:', err);
      setServerError(err.message || 'Failed to enroll field plot.');
      setIsSubmitting(false);
    }
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      size="md"
      title="Enroll New Field Plot"
      subtitle="Register an individual sugarcane field and assign its field owner."
      badge="Field Parcel Allocation"
      icon={Layers}
      preventBackdropClose={isSubmitting}
      preventEscapeClose={isSubmitting}
      footer={
        <>
          <Button
            variant="secondary"
            onClick={onClose}
            disabled={isSubmitting}
          >
            Cancel
          </Button>
          <Button
            variant="primary"
            onClick={handleSubmit}
            isLoading={isSubmitting}
            loadingText="Saving field..."
          >
            Enroll Field Plot
          </Button>
        </>
      }
    >
      <form onSubmit={handleSubmit} className="space-y-4">
        {serverError && (
          <div className="p-3 bg-danger-bg dark:bg-danger/20 border border-danger/30 rounded-xl text-xs font-bold text-danger">
            {serverError}
          </div>
        )}

        {/* 1. Plot ID & Block Farm */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
          <FormField
            id="field-id-input"
            label="Field Plot ID"
            helperText="Generated by the server after enrollment."
          >
            <Input
              id="field-id-input"
              value="Generated automatically"
              readOnly
              disabled
            />
          </FormField>

          <FormField
            id="block-farm-select"
            label="Parent Block Farm"
            required
            error={errors.blockFarmId}
          >
            <Select
              id="block-farm-select"
              value={blockFarmId || defaultBlockFarmId}
              onChange={handleBlockFarmChange}
              disabled={isSubmitting || blockFarms.length === 0}
              placeholder="Select Block Farm..."
              options={blockFarms.map(bf => ({
                value: bf.id,
                label: `${bf.name} (${bf.code || bf.id})`
              }))}
            />
          </FormField>
        </div>

        {/* 2. Assigned Farm Member */}
        <FormField
          id="member-user-select"
          label="Assigned Field Owner"
          helperText="Select a registered Farm Member or assign your own manager field."
        >
          <Select
            id="member-user-select"
            value={memberUserId}
            onChange={(e) => setMemberUserId(e.target.value)}
            disabled={isSubmitting}
            placeholder="Unassigned (Can assign later)..."
            options={memberUsers.map(m => ({
              value: m.id || m.employeeId,
              label: `${m.displayName || m.name} (${m.phone || m.id})`
            }))}
          />
        </FormField>

        {/* 3. Persistent parcel attributes */}
        <div>
          <FormField
            id="area-ha-input"
            label="Plot Area"
            required
            error={errors.areaHa}
          >
            <Input
              id="area-ha-input"
              type="number"
              step="0.01"
              min="0.01"
              max="500"
              placeholder="1.50"
              suffix="ha"
              value={areaHa}
              onChange={(e) => {
                setAreaHa(e.target.value);
                if (errors.areaHa) setErrors(prev => ({ ...prev, areaHa: null }));
              }}
              error={Boolean(errors.areaHa)}
              disabled={isSubmitting}
            />
          </FormField>

        </div>

        {/* 4. Server-generated Crop Year Cycle */}
        <div>
          <FormField
            id="crop-year-cycle-preview"
            label="Crop Year Cycle"
            helperText="Preview only. The server sets the canonical year when the field is enrolled."
          >
            <Input
              id="crop-year-cycle-preview"
              value={CROP_YEAR_PREVIEW}
              readOnly
              disabled
            />
          </FormField>
        </div>
      </form>
    </Modal>
  );
}
