'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {
  SYSTEM_ID_PATTERN,
  createBlockFarmId,
  createFieldId,
  assertNoClientIdentity
} = require('../domain/systemIds');

const read = relativePath => fs.readFileSync(path.resolve(__dirname, relativePath), 'utf8');

class MemoryRef {
  constructor(database, collection, id) {
    this.database = database;
    this.collection = collection;
    this.id = id;
  }
  async get() {
    const value = this.database.records.get(this.collection)?.get(this.id);
    return { exists: value !== undefined, id: this.id, data: () => value && { ...value }, ref: this };
  }
  async create(value) {
    this.database.create(this, value);
  }
}

class MemoryQuery {
  constructor(database, collection, filters = []) {
    this.database = database;
    this.collection = collection;
    this.filters = filters;
  }
  doc(id) {
    return new MemoryRef(this.database, this.collection, id);
  }
  where(field, operator, value) {
    assert.equal(operator, '==');
    return new MemoryQuery(this.database, this.collection, [...this.filters, { field, value }]);
  }
  async get() {
    const rows = [...(this.database.records.get(this.collection) || new Map()).entries()]
      .filter(([, value]) => this.filters.every(filter => value[filter.field] === filter.value));
    return {
      empty: rows.length === 0,
      docs: rows.map(([id, value]) => ({ id, data: () => ({ ...value }) }))
    };
  }
}

class MemoryDb {
  constructor(seed = {}) {
    this.records = new Map(Object.entries(seed).map(([collection, records]) => [collection, new Map(Object.entries(records))]));
  }
  collection(name) {
    return new MemoryQuery(this, name);
  }
  create(ref, value) {
    if (!this.records.has(ref.collection)) this.records.set(ref.collection, new Map());
    const records = this.records.get(ref.collection);
    if (records.has(ref.id)) throw new Error('already exists');
    records.set(ref.id, { ...value });
  }
  batch() {
    const creates = [];
    return {
      create: (ref, value) => creates.push({ ref, value }),
      commit: async () => {
        for (const item of creates) this.create(item.ref, item.value);
      }
    };
  }
}

function responseCapture() {
  return {
    statusCode: 200,
    payload: null,
    status(code) { this.statusCode = code; return this; },
    json(payload) { this.payload = payload; return this; }
  };
}

function loadHandler(routeRelativePath, db, routePathValue = '/', method = 'post') {
  const firebasePath = require.resolve('../firebase-admin');
  const routePath = require.resolve(routeRelativePath);
  const previousFirebase = require.cache[firebasePath];
  delete require.cache[routePath];
  require.cache[firebasePath] = { id: firebasePath, filename: firebasePath, loaded: true, exports: { db } };
  const router = require(routeRelativePath);
  if (previousFirebase) require.cache[firebasePath] = previousFirebase;
  else delete require.cache[firebasePath];
  return router.stack.find(layer => layer.route?.path === routePathValue && layer.route.methods[method]).route.stack.at(-1).handle;
}

async function invoke(handler, body, user, params = {}) {
  const response = responseCapture();
  await handler({ body, params, session: { user }, get: () => '' }, response);
  return response;
}

test('server-issued Block Farm and Field IDs are formatted and collision-resistant across concurrent requests', async () => {
  const generated = await Promise.all(Array.from({ length: 2000 }, async (_, index) => (
    index % 2 === 0 ? createBlockFarmId() : createFieldId()
  )));
  assert.equal(new Set(generated).size, generated.length);
  assert.ok(generated.every(id => SYSTEM_ID_PATTERN.test(id)));
  assert.ok(generated.some(id => id.startsWith('BF-')));
  assert.ok(generated.some(id => id.startsWith('FLD-')));
});

test('ordinary clients cannot provide or change canonical entity identity', () => {
  assert.throws(
    () => assertNoClientIdentity({ id: 'FLD-MANUAL' }, ['id', 'fieldId'], 'Field'),
    /generated by the server/
  );
  assert.throws(
    () => assertNoClientIdentity({ code: 'BF-MANUAL' }, ['id', 'blockFarmId', 'code'], 'Block Farm'),
    /generated by the server/
  );
  assert.doesNotThrow(() => assertNoClientIdentity({ name: 'Legitimate Name' }, ['id'], 'Field'));
});

test('Field and Block Farm create endpoints return distinct server IDs and reject chosen IDs', async () => {
  const db = new MemoryDb({
    block_farms: {
      'BF-EXISTING': { managerUserId: '03000001', status: 'ACTIVE' }
    }
  });
  const fieldPost = loadHandler('../routes/fields', db);
  const fieldPatch = loadHandler('../routes/fields', db, '/:id', 'patch');
  const farmPost = loadHandler('../routes/blockFarms', db);
  const farmPut = loadHandler('../routes/blockFarms', db, '/:id', 'put');
  const manager = { employeeId: '03000001', role: 'FARM_MANAGER' };
  const sra = { employeeId: '02000001', role: 'SRA_ADMIN' };

  const fieldBody = { blockFarmId: 'BF-EXISTING', memberUserId: null, areaHa: 1.25 };
  const [fieldA, fieldB] = await Promise.all([
    invoke(fieldPost, fieldBody, manager),
    invoke(fieldPost, fieldBody, manager)
  ]);
  assert.equal(fieldA.statusCode, 201);
  assert.equal(fieldB.statusCode, 201);
  assert.notEqual(fieldA.payload.data.field.id, fieldB.payload.data.field.id);
  assert.match(fieldA.payload.data.field.id, /^FLD-/);
  assert.equal(fieldA.payload.data.cycle.fieldId, fieldA.payload.data.field.id);
  assert.equal(Object.prototype.hasOwnProperty.call(fieldA.payload.data.field, 'soilType'), false);
  assert.equal((await invoke(fieldPost, { ...fieldBody, id: 'FLD-MANUAL' }, manager)).statusCode, 400);
  assert.equal((await invoke(fieldPatch, { id: 'FLD-REWRITTEN' }, manager, { id: fieldA.payload.data.field.id })).statusCode, 400);

  const farmBody = { name: 'Server ID Farm', location: 'Negros Occidental', declaredAreaHa: 5, managerUserId: null };
  const [farmA, farmB] = await Promise.all([
    invoke(farmPost, farmBody, sra),
    invoke(farmPost, farmBody, sra)
  ]);
  assert.equal(farmA.statusCode, 201);
  assert.equal(farmB.statusCode, 201);
  assert.notEqual(farmA.payload.data.id, farmB.payload.data.id);
  assert.equal(farmA.payload.data.code, farmA.payload.data.id);
  assert.equal((await invoke(farmPost, { ...farmBody, id: 'BF-MANUAL', code: 'BF-MANUAL' }, sra)).statusCode, 400);
  assert.equal((await invoke(farmPut, { code: 'BF-REWRITTEN' }, sra, { id: farmA.payload.data.id })).statusCode, 400);
});

test('server routes own create identity and reject identity changes on edit', () => {
  const fieldsRoute = read('../routes/fields.js');
  const farmsRoute = read('../routes/blockFarms.js');
  const usersRoute = read('../routes/users.js');
  assert.match(fieldsRoute, /const fieldId = developmentSeedId \|\| createFieldId\(\)/);
  assert.match(fieldsRoute, /assertNoClientIdentity\(req\.body, \['id', 'fieldId'\], 'Field'\)/);
  assert.doesNotMatch(fieldsRoute, /requiredString\(req\.body\.id/);
  assert.match(farmsRoute, /const blockFarmId = developmentSeedId \|\| createBlockFarmId\(\)/);
  assert.match(farmsRoute, /assertNoClientIdentity\(req\.body, \['id', 'blockFarmId', 'code'\], 'Block Farm'\)/);
  assert.match(farmsRoute, /code: blockFarmId/);
  assert.match(usersRoute, /assertNoClientIdentity\(req\.body, \['id', 'userId', 'employeeId'\], 'User'\)/);
});

test('Web and Android create forms never generate or submit canonical IDs', () => {
  const webField = read('../../web/react-app/src/components/fields/FieldEnrollmentModal.jsx');
  const webFarm = read('../../web/react-app/src/components/fields/BlockFarmModal.jsx');
  const mobileScreen = read('../../mobile/src/screens/FieldOpsScreen.js');
  const mobileStore = read('../../mobile/src/data/dataStore.js');
  const mobileMutations = read('../../mobile/src/services/mutationService.js');

  assert.doesNotMatch(webField, /setFieldId|id:\s*cleanId|highest \+ 1/);
  assert.match(webField, /Generated by the server after enrollment/);
  assert.doesNotMatch(webFarm, /setCode|id:\s*cleanCode|code:\s*cleanCode/);
  assert.match(webFarm, /Permanent server-issued identifier/);
  assert.doesNotMatch(mobileScreen, /generateNextFieldId|placeholder="e\.g\. 04000001/);
  assert.match(mobileScreen, /Generated after enrollment/);
  assert.match(mobileStore, /New Field enrollment requires a live connection/);
  assert.match(mobileStore, /authenticatedRequest\('\/api\/fields'/);
  assert.doesNotMatch(mobileStore, /export const generateNextFieldId/);
  assert.match(mobileMutations, /id: _ignoredId, fieldId: _ignoredFieldId/);
});

test('offline operation and outbox identities remain stable while Field creation is online-only', () => {
  const syncEngine = read('../../mobile/src/services/syncEngine.js');
  const outbox = read('../../mobile/src/services/mutationOutboxCore.js');
  assert.match(syncEngine, /generateDeterministicLogId/);
  assert.match(outbox, /idempotencyKey: mutationId/);
  assert.match(outbox, /appendUniqueMutation/);
});
